package hostserver

import (
	"bytes"
	"testing"

	"github.com/complacentsee/go-db2i/internal/wirelog"
)

// TestSignOnUppercasesUserID confirms SignOn normalises the userID
// to upper case before sending the SignonInfoRequest. IBM i user
// profiles are stored uppercase; failing to normalise causes the
// auth-bytes hash (computed from the userID) to mismatch what the
// server computes after its own normalisation, returning SQL
// -3008 ("password incorrect") -- a confusing error since the
// password itself is fine.
//
// We can't replay a captured fixture for this case (the captured
// fixtures all use already-uppercase user IDs), so the structural
// check is: send userID="gotest" through SignOn, intercept the
// SignonInfoRequest bytes, parse out the user-ID CP (0x1104), and
// confirm it carries EBCDIC "GOTEST    " (uppercase).
func TestSignOnUppercasesUserID(t *testing.T) {
	// Pre-canned replies from connect_only.trace work for any
	// userID since the auth bytes (which depend on userID) are
	// generated by SignOn and we don't validate them server-side
	// here -- we only validate what the SignOn function WROTE.
	frames := wirelog.Consolidate(loadFixture(t, "connect_only.trace"))
	var receiveds [][]byte
	for _, f := range frames {
		if f.Direction == wirelog.Received {
			receiveds = append(receiveds, f.Bytes)
		}
	}
	if len(receiveds) < 2 {
		t.Fatalf("need >= 2 received frames, got %d", len(receiveds))
	}

	conn := newFakeConn(receiveds[0], receiveds[1])
	if _, _, err := SignOn(conn, "gotest", "any-password"); err != nil {
		t.Fatalf("SignOn err: %v", err)
	}

	// Locate the user-ID CP (0x1104) in the second written frame
	// (the SignonInfoRequest). EBCDIC "GOTEST    " is the
	// expected payload: G=0xC7 O=0xD6 T=0xE3 E=0xC5 S=0xE2 T=0xE3
	// + 4 EBCDIC spaces (0x40).
	written := conn.written.Bytes()
	wantUserBytes := []byte{0xC7, 0xD6, 0xE3, 0xC5, 0xE2, 0xE3, 0x40, 0x40, 0x40, 0x40}
	if !bytes.Contains(written, wantUserBytes) {
		t.Errorf("SignOn did not uppercase userID -- expected %x in written bytes", wantUserBytes)
	}
	// And confirm the lowercase form did NOT make it onto the wire.
	wantLower := []byte{0x87, 0x96, 0xa3, 0x85, 0xa2, 0xa3} // "gotest" EBCDIC lowercase
	if bytes.Contains(written, wantLower) {
		t.Errorf("SignOn leaked lowercase userID onto the wire (%x)", wantLower)
	}
}

// extractUserIDCP scans a written request stream for the 10-byte
// EBCDIC user-ID CP (0x1104) and returns its payload. Both the
// as-signon (SignonInfoRequest) and as-database (StartServerRequest)
// flows emit this exact CP, so the same scanner works for both.
func extractUserIDCP(t *testing.T, written []byte) []byte {
	t.Helper()
	// CP layout on the wire: LL(4) = 0x00000010, CP(2) = 0x1104,
	// data(10). Find the CP marker (LL prefix + CP) and slice the data.
	marker := []byte{0x00, 0x00, 0x00, 0x10, 0x11, 0x04}
	i := bytes.Index(written, marker)
	if i < 0 {
		t.Fatalf("user-ID CP (0x1104) not found in written bytes")
	}
	start := i + len(marker)
	if start+10 > len(written) {
		t.Fatalf("user-ID CP truncated: only %d bytes after marker", len(written)-start)
	}
	return append([]byte(nil), written[start:start+10]...)
}

// TestSignOnAndStartDatabaseUserIDBytesMatch is the offline
// acceptance check for issue #33: a mixed-case DSN userID must be
// normalised to the SAME uppercase bytes by BOTH the as-signon (8476)
// and as-database (8471) handshakes. Before the fix, SignOn
// uppercased but StartDatabaseService did not, so the two services
// hashed different bytes and a mixed-case user that signed on then
// failed the database auth.
//
// We drive both flows with userID="GoTest" using each service's own
// captured replies, pull the on-wire user-ID CP (0x1104) out of each,
// and assert they are byte-identical (uppercase EBCDIC "GOTEST    ").
// Because EncryptPasswordSHA1 hashes this same normalised userID,
// equal user-ID CP bytes imply equal auth-hash inputs across flows.
func TestSignOnAndStartDatabaseUserIDBytesMatch(t *testing.T) {
	const mixedUser = "GoTest"

	// as-signon replies: the first two Received frames overall.
	frames := wirelog.Consolidate(loadFixture(t, "connect_only.trace"))
	var signonReplies [][]byte
	for _, f := range frames {
		if f.Direction == wirelog.Received {
			signonReplies = append(signonReplies, f.Bytes)
			if len(signonReplies) == 2 {
				break
			}
		}
	}
	if len(signonReplies) < 2 {
		t.Fatalf("need >= 2 as-signon received frames, got %d", len(signonReplies))
	}

	signonConn := newFakeConn(signonReplies[0], signonReplies[1])
	if _, _, err := SignOn(signonConn, mixedUser, "any-password"); err != nil {
		t.Fatalf("SignOn err: %v", err)
	}
	signonUserBytes := extractUserIDCP(t, signonConn.written.Bytes())

	// as-database replies: the as-database connection's frames.
	dbReceiveds := dbReceivedsFromFixture(t, "connect_only.trace")
	dbConn := newFakeConn(dbReceiveds[0].Bytes, dbReceiveds[1].Bytes)
	if _, _, err := StartDatabaseService(dbConn, mixedUser, "any-password"); err != nil {
		t.Fatalf("StartDatabaseService err: %v", err)
	}
	dbUserBytes := extractUserIDCP(t, dbConn.written.Bytes())

	// EBCDIC "GOTEST    " (CCSID 37): uppercase + 4 spaces.
	wantUpper := []byte{0xC7, 0xD6, 0xE3, 0xC5, 0xE2, 0xE3, 0x40, 0x40, 0x40, 0x40}

	if !bytes.Equal(signonUserBytes, dbUserBytes) {
		t.Errorf("user-ID bytes differ across flows:\n  SignOn               = %x\n  StartDatabaseService = %x",
			signonUserBytes, dbUserBytes)
	}
	if !bytes.Equal(signonUserBytes, wantUpper) {
		t.Errorf("SignOn user-ID bytes = %x, want uppercase EBCDIC %x", signonUserBytes, wantUpper)
	}
	if !bytes.Equal(dbUserBytes, wantUpper) {
		t.Errorf("StartDatabaseService user-ID bytes = %x, want uppercase EBCDIC %x", dbUserBytes, wantUpper)
	}
}
