package hostserver

import (
	"bytes"
	"testing"

	"github.com/complacentsee/go-db2i/internal/wirelog"
)

// TestSignOnUppercasesUserID confirms SignOn normalises the userID
// to upper case before sending the SignonInfoRequest. IBM i user
// profiles are stored uppercase; failing to normalise causes the
// auth-bytes hash (computed from the userID) to mismatch what the
// server computes after its own normalisation, returning SQL
// -3008 ("password incorrect") -- a confusing error since the
// password itself is fine.
//
// We can't replay a captured fixture for this case (the captured
// fixtures all use already-uppercase user IDs), so the structural
// check is: send userID="gotest" through SignOn, intercept the
// SignonInfoRequest bytes, parse out the user-ID CP (0x1104), and
// confirm it carries EBCDIC "GOTEST    " (uppercase).
func TestSignOnUppercasesUserID(t *testing.T) {
	// Pre-canned replies from connect_only.trace work for any
	// userID since the auth bytes (which depend on userID) are
	// generated by SignOn and we don't validate them server-side
	// here -- we only validate what the SignOn function WROTE.
	frames := wirelog.Consolidate(loadFixture(t, "connect_only.trace"))
	var receiveds [][]byte
	for _, f := range frames {
		if f.Direction == wirelog.Received {
			receiveds = append(receiveds, f.Bytes)
		}
	}
	if len(receiveds) < 2 {
		t.Fatalf("need >= 2 received frames, got %d", len(receiveds))
	}

	conn := newFakeConn(receiveds[0], receiveds[1])
	if _, _, err := SignOn(conn, "gotest", "any-password"); err != nil {
		t.Fatalf("SignOn err: %v", err)
	}

	// Locate the user-ID CP (0x1104) in the second written frame
	// (the SignonInfoRequest). EBCDIC "GOTEST    " is the
	// expected payload: G=0xC7 O=0xD6 T=0xE3 E=0xC5 S=0xE2 T=0xE3
	// + 4 EBCDIC spaces (0x40).
	written := conn.written.Bytes()
	wantUserBytes := []byte{0xC7, 0xD6, 0xE3, 0xC5, 0xE2, 0xE3, 0x40, 0x40, 0x40, 0x40}
	if !bytes.Contains(written, wantUserBytes) {
		t.Errorf("SignOn did not uppercase userID -- expected %x in written bytes", wantUserBytes)
	}
	// And confirm the lowercase form did NOT make it onto the wire.
	wantLower := []byte{0x87, 0x96, 0xa3, 0x85, 0xa2, 0xa3} // "gotest" EBCDIC lowercase
	if bytes.Contains(written, wantLower) {
		t.Errorf("SignOn leaked lowercase userID onto the wire (%x)", wantLower)
	}
}
