package driver_test

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"time"

	db2i "github.com/complacentsee/go-db2i/driver"
	"github.com/complacentsee/go-db2i/hostserver"
)

// Example shows the typical sql.Open + db.Query path. The driver
// registers itself as "db2i" via init() so anonymous import is
// enough to make sql.Open accept the db2i:// DSN scheme.
func Example() {
	dsn := "db2i://USER:PASSWORD@host.example.com:8471/?library=MYLIB"
	db, err := sql.Open("db2i", dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	rows, err := db.Query(`SELECT id, label FROM mylib.things WHERE status = ?`, "OPEN")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	for rows.Next() {
		var id int64
		var label string
		if err := rows.Scan(&id, &label); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%d %s\n", id, label)
	}
	if err := rows.Err(); err != nil {
		log.Fatal(err)
	}
}

// ExampleDB_query_largeResult demonstrates that result-set
// iteration is lazy: a 10-million-row SELECT pulls one batch
// (~32 KB) at a time via continuation FETCH instead of buffering
// everything. The caller's loop drives the wire round-trips.
func Example_largeResult() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	rows, _ := db.Query(`SELECT TABLE_NAME, COLUMN_NAME FROM QSYS2.SYSCOLUMNS`)
	defer rows.Close()

	count := 0
	for rows.Next() {
		var t, c string
		_ = rows.Scan(&t, &c)
		count++
	}
	fmt.Printf("scanned %d rows\n", count)
}

// Example_transaction exercises commitment-control: db.Begin
// switches the session out of *NONE into *CS, runs the bracketed
// statements, and tx.Commit / tx.Rollback restore the autocommit-
// permissive baseline.
func Example_transaction() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB&isolation=cs")
	defer db.Close()

	tx, err := db.Begin()
	if err != nil {
		log.Fatal(err)
	}
	if _, err := tx.Exec(`UPDATE mylib.things SET status = ? WHERE id = ?`, "DONE", 42); err != nil {
		_ = tx.Rollback()
		log.Fatal(err)
	}
	if err := tx.Commit(); err != nil {
		log.Fatal(err)
	}
}

// Example_lastInsertId shows that LastInsertId() returns the
// IDENTITY value generated by the most recent IDENTITY-bearing
// INSERT on the session, via a follow-up VALUES IDENTITY_VAL_LOCAL()
// round trip. The first call hits the wire; subsequent calls return
// the cached value.
func Example_lastInsertId() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	res, err := db.Exec(`INSERT INTO mylib.things (label) VALUES (?)`, "new thing")
	if err != nil {
		log.Fatal(err)
	}
	id, err := res.LastInsertId()
	if err != nil {
		// ErrNoLastInsertId: the session has never run an INSERT
		// against an IDENTITY column.
		log.Fatal(err)
	}
	fmt.Println(id)
}

// Example_call demonstrates calling a stored procedure with IN-only
// parameters. go-db2i routes any SQL starting with "CALL " through
// the same CREATE_RPB + PREPARE_DESCRIBE + EXECUTE flow JT400 uses
// for CallableStatement, with statement type 3 (TYPE_CALL) on both
// PREPARE and EXECUTE. M9-1 covers IN-only; OUT / INOUT via sql.Out
// lands in M9-2, multi-result-set procs via rows.NextResultSet() in
// M9-3.
//
// For procs that take no parameters or carry literal arguments
// inline (e.g. `CALL P_BUMP('A', 10)`), db.Exec still works -- the
// driver detects the CALL verb and routes through ExecutePreparedSQL
// rather than ExecuteImmediate so the server sees TYPE_CALL on
// PREPARE. This is required for correct SQLERRD(2) population when
// the proc returns dynamic result sets.
func Example_call() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	// IN-only stored procedure: arguments flow through driver.Value
	// the same as any other prepared statement.
	_, err := db.Exec(`CALL mylib.bump_counter(?, ?)`, "WIDGET", 1)
	if err != nil {
		log.Fatal(err)
	}
}

// Example_callWithOut demonstrates OUT and INOUT parameter handling
// via the database/sql sql.Out wrapper. go-db2i sets the
// JT400-compatible direction byte (0xF1 for OUT, 0xF2 for INOUT) at
// descriptor offset 30, ORs the ORS_RESULT_DATA bit into the EXECUTE
// request so the server ships a synthetic single-row CP 0x380E
// reply, and reflect-assigns the decoded values back to the caller's
// destinations after EXECUTE returns. Go 1.21+ is required for the
// sql.Out.In INOUT field; go-db2i's go.mod floor is 1.23 so this
// is always available.
func Example_callWithOut() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	// IN VARCHAR + OUT VARCHAR + OUT INTEGER (e.g. a P_LOOKUP proc
	// that SELECTs the matching row into the OUT params).
	var name string
	var qty int
	if _, err := db.Exec(`CALL mylib.p_lookup(?, ?, ?)`,
		"WIDGET",
		sql.Out{Dest: &name},
		sql.Out{Dest: &qty},
	); err != nil {
		log.Fatal(err)
	}
	fmt.Println(name, qty) // "Acme Widget 100"

	// INOUT INTEGER: bind value flows in via *Dest, server-returned
	// value flows back to the same destination on the OUT side.
	counter := 5
	if _, err := db.Exec(`CALL mylib.p_increment(?)`,
		sql.Out{Dest: &counter, In: true},
	); err != nil {
		log.Fatal(err)
	}
	fmt.Println(counter) // 6
}

// Example_callMultiResultSet demonstrates draining a stored
// procedure that declares DYNAMIC RESULT SETS N (multiple cursors
// opened via DECLARE CURSOR WITH RETURN). go-db2i drains each set
// through database/sql's Rows.NextResultSet idiom: the first set
// is iterated via Rows.Next as usual, then NextResultSet attaches
// to the next pre-opened cursor on the server side and Rows.Next
// continues from there. Returns true while more sets remain;
// false (or io.EOF) when the proc's last set is drained.
func Example_callMultiResultSet() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	rows, _ := db.Query(`CALL mylib.p_inventory(?)`, 5)
	defer rows.Close()

	fmt.Println("low-stock items:")
	for rows.Next() {
		var code string
		var qty int
		_ = rows.Scan(&code, &qty)
		fmt.Printf("  %s: %d\n", code, qty)
	}

	if rows.NextResultSet() {
		fmt.Println("high-stock items:")
		for rows.Next() {
			var code string
			var qty int
			_ = rows.Scan(&code, &qty)
			fmt.Printf("  %s: %d\n", code, qty)
		}
	}
}

// Example_db2Error shows the typed-error dispatch pattern. Every
// server-side SQL error comes through as *hostserver.Db2Error so
// callers can switch on SQLSTATE / SQLCODE without regexing the
// formatted message.
func Example_db2Error() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	_, err := db.Exec(`INSERT INTO mylib.things (id) VALUES (?)`, 42)
	if err == nil {
		return
	}
	var dbErr *hostserver.Db2Error
	if !errors.As(err, &dbErr) {
		log.Fatal(err) // not a server-side SQL error -- TCP-level, etc.
	}
	switch {
	case dbErr.IsNotFound():
		// SQLSTATE 02xxx -- no rows matched
	case dbErr.IsConstraintViolation():
		// SQLSTATE 23xxx -- duplicate key, NOT NULL, FK, check
		fmt.Printf("constraint: %s tokens=%v\n", dbErr.SQLState, dbErr.MessageTokens)
	case dbErr.IsLockTimeout():
		// SQLCODE -911/-913 -- safe to retry with backoff
	case dbErr.IsConnectionLost():
		// SQLSTATE 08xxx -- pool will retire the conn
	default:
		log.Printf("SQL%d %s %s: %s", dbErr.SQLCode, dbErr.SQLState, dbErr.MessageID, dbErr.Message)
	}
}

// Example_blobInsert shows binding a BLOB column via a `?` placeholder.
// Small payloads can pass as a plain []byte; the driver detects the
// LOB column from the server-side parameter marker format and routes
// the bytes through a single WRITE_LOB_DATA frame, then EXECUTE
// carries the locator handle in the SQLDA value slot.
func Example_blobInsert() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	payload := []byte{0xCA, 0xFE, 0xBA, 0xBE} // up to a few KB; bigger uses LOBValue
	if _, err := db.Exec(
		`INSERT INTO mylib.images (id, content) VALUES (?, ?)`, 42, payload,
	); err != nil {
		log.Fatal(err)
	}
}

// Example_lobValueStream shows the streamed bind path for large LOBs.
// The driver reads from the io.Reader in 32 KiB chunks and emits
// multiple WRITE_LOB_DATA frames at advancing offsets so the entire
// payload never needs to live in Go memory at once. Length must be
// known up front because the IBM i host server allocates locator
// buffers based on the declared size.
func Example_lobValueStream() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	f, err := os.Open("backup.tar.gz")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	stat, err := f.Stat()
	if err != nil {
		log.Fatal(err)
	}

	val := &db2i.LOBValue{Reader: f, Length: stat.Size()}
	if _, err := db.Exec(
		`INSERT INTO mylib.archives (id, blob) VALUES (?, ?)`, 1, val,
	); err != nil {
		log.Fatal(err)
	}
}

// Example_clobInsert binds a CLOB column. The driver transcodes the
// Go string to the column's declared CCSID via the per-CCSID codec
// in package ebcdic (CCSID 273 / German EBCDIC on a German PUB400
// account, CCSID 37 / US English on a US system, etc.) so EBCDIC
// code-point quirks ("!" = 0x5A in CCSID 37 but 0x4F in CCSID 273)
// round-trip cleanly through the matching read decoder.
func Example_clobInsert() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	doc := "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " +
		"... entire document up to the column's max ..."
	if _, err := db.Exec(
		`INSERT INTO mylib.docs (id, body) VALUES (?, ?)`, 7, doc,
	); err != nil {
		log.Fatal(err)
	}
}

// Example_lobReader streams a BLOB out of a SELECT one chunk at a
// time. The DSN option `?lob=stream` flips the default scan-into-
// []byte behaviour to scan-into-*LOBReader for LOB columns; the
// reader satisfies io.Reader+io.Closer and pulls 32 KiB chunks per
// Read call. Pair with Example_lobValueStream for the bind side.
func Example_lobReader() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB&lob=stream")
	defer db.Close()

	row := db.QueryRow(`SELECT content FROM mylib.images WHERE id = ?`, 42)
	var r *db2i.LOBReader
	if err := row.Scan(&r); err != nil {
		log.Fatal(err)
	}
	defer r.Close()

	if _, err := io.Copy(os.Stdout, r); err != nil {
		log.Fatal(err)
	}
}

// Example_dsnKnobs exercises the three most commonly tuned DSN knobs
// at once: ?lob-threshold=N caps the inline-LOB cutoff the server
// uses for parameter-marker writes (matching JT400's "lob threshold"
// JDBC property), ?ccsid=1208 forces UTF-8 on the application-data
// CCSID so non-ASCII characters round-trip without locale-dependent
// EBCDIC ambiguity, and ?tls=true wraps both as-signon and
// as-database sockets in crypto/tls (flipping the default ports to
// 9476 / 9471). The keys are independent -- mix and match per
// deployment.
func Example_dsnKnobs() {
	dsn := "db2i://USER:PASSWORD@host.example.com/" +
		"?library=MYLIB" +
		"&lob-threshold=8192" +
		"&ccsid=1208" +
		"&tls=true" +
		"&tls-server-name=host.example.com"
	db, err := sql.Open("db2i", dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	_ = db.Ping()
}

// Example_contextTimeout shows that QueryContext / ExecContext
// honor ctx cancellation. A canceled ctx unblocks the in-flight
// host-server read via net.Conn.SetDeadline; the call returns
// context.DeadlineExceeded / context.Canceled regardless of which
// I/O step bailed.
func Example_contextTimeout() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	rows, err := db.QueryContext(ctx, `SELECT * FROM huge.table`)
	if errors.Is(err, context.DeadlineExceeded) {
		log.Println("query took longer than 5s; pool will replace the conn")
		return
	}
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
}
