package driver_test

import (
	"bytes"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"log"
	"log/slog"
	"os"
	"strings"
	"time"

	db2i "github.com/complacentsee/go-db2i/driver"
	"github.com/complacentsee/go-db2i/hostserver"
)

// Example shows the typical sql.Open + db.Query path. The driver
// registers itself as "db2i" via init() so anonymous import is
// enough to make sql.Open accept the db2i:// DSN scheme.
func Example() {
	dsn := "db2i://USER:PASSWORD@host.example.com:8471/?library=MYLIB"
	db, err := sql.Open("db2i", dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	rows, err := db.Query(`SELECT id, label FROM mylib.things WHERE status = ?`, "OPEN")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	for rows.Next() {
		var id int64
		var label string
		if err := rows.Scan(&id, &label); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%d %s\n", id, label)
	}
	if err := rows.Err(); err != nil {
		log.Fatal(err)
	}
}

// ExampleDB_query_largeResult demonstrates that result-set
// iteration is lazy: a 10-million-row SELECT pulls one batch
// (~32 KB) at a time via continuation FETCH instead of buffering
// everything. The caller's loop drives the wire round-trips.
func Example_largeResult() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	rows, _ := db.Query(`SELECT TABLE_NAME, COLUMN_NAME FROM QSYS2.SYSCOLUMNS`)
	defer rows.Close()

	count := 0
	for rows.Next() {
		var t, c string
		_ = rows.Scan(&t, &c)
		count++
	}
	fmt.Printf("scanned %d rows\n", count)
}

// Example_transaction exercises commitment-control: db.Begin
// switches the session out of *NONE into *CS, runs the bracketed
// statements, and tx.Commit / tx.Rollback restore the autocommit-
// permissive baseline.
func Example_transaction() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB&isolation=cs")
	defer db.Close()

	tx, err := db.Begin()
	if err != nil {
		log.Fatal(err)
	}
	if _, err := tx.Exec(`UPDATE mylib.things SET status = ? WHERE id = ?`, "DONE", 42); err != nil {
		_ = tx.Rollback()
		log.Fatal(err)
	}
	if err := tx.Commit(); err != nil {
		log.Fatal(err)
	}
}

// Example_lastInsertId shows that LastInsertId() returns the
// IDENTITY value generated by the most recent IDENTITY-bearing
// INSERT on the session, via a follow-up VALUES IDENTITY_VAL_LOCAL()
// round trip. The first call hits the wire; subsequent calls return
// the cached value.
func Example_lastInsertId() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	res, err := db.Exec(`INSERT INTO mylib.things (label) VALUES (?)`, "new thing")
	if err != nil {
		log.Fatal(err)
	}
	id, err := res.LastInsertId()
	if err != nil {
		// ErrNoLastInsertId: the session has never run an INSERT
		// against an IDENTITY column.
		log.Fatal(err)
	}
	fmt.Println(id)
}

// Example_call demonstrates calling a stored procedure with IN-only
// parameters. The driver detects the leading CALL verb and prepares
// the statement with TYPE_CALL so the server returns the correct
// metadata, even for procs with no parameter markers or only
// literal arguments inline (e.g. `CALL P_BUMP('A', 10)`).
func Example_call() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	// IN-only stored procedure: arguments flow through driver.Value
	// the same as any other prepared statement.
	_, err := db.Exec(`CALL mylib.bump_counter(?, ?)`, "WIDGET", 1)
	if err != nil {
		log.Fatal(err)
	}
}

// Example_callWithOut demonstrates OUT and INOUT parameter handling
// via the database/sql sql.Out wrapper. The driver tags each marker
// with its direction on the wire, asks the server to ship the
// returned values back as a synthetic single-row reply, and
// reflect-assigns the decoded values into the caller's destinations
// when EXECUTE returns.
func Example_callWithOut() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	// IN VARCHAR + OUT VARCHAR + OUT INTEGER (e.g. a P_LOOKUP proc
	// that SELECTs the matching row into the OUT params).
	var name string
	var qty int
	if _, err := db.Exec(`CALL mylib.p_lookup(?, ?, ?)`,
		"WIDGET",
		sql.Out{Dest: &name},
		sql.Out{Dest: &qty},
	); err != nil {
		log.Fatal(err)
	}
	fmt.Println(name, qty) // "Acme Widget 100"

	// INOUT INTEGER: bind value flows in via *Dest, server-returned
	// value flows back to the same destination on the OUT side.
	counter := 5
	if _, err := db.Exec(`CALL mylib.p_increment(?)`,
		sql.Out{Dest: &counter, In: true},
	); err != nil {
		log.Fatal(err)
	}
	fmt.Println(counter) // 6
}

// Example_callMultiResultSet demonstrates draining a stored
// procedure that declares DYNAMIC RESULT SETS N (multiple cursors
// opened via DECLARE CURSOR WITH RETURN). go-db2i drains each set
// through database/sql's Rows.NextResultSet idiom: the first set
// is iterated via Rows.Next as usual, then NextResultSet attaches
// to the next pre-opened cursor on the server side and Rows.Next
// continues from there. Returns true while more sets remain;
// false (or io.EOF) when the proc's last set is drained.
func Example_callMultiResultSet() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	rows, _ := db.Query(`CALL mylib.p_inventory(?)`, 5)
	defer rows.Close()

	fmt.Println("low-stock items:")
	for rows.Next() {
		var code string
		var qty int
		_ = rows.Scan(&code, &qty)
		fmt.Printf("  %s: %d\n", code, qty)
	}

	if rows.NextResultSet() {
		fmt.Println("high-stock items:")
		for rows.Next() {
			var code string
			var qty int
			_ = rows.Scan(&code, &qty)
			fmt.Printf("  %s: %d\n", code, qty)
		}
	}
}

// Example_db2Error shows the typed-error dispatch pattern. Every
// server-side SQL error comes through as *hostserver.Db2Error so
// callers can switch on SQLSTATE / SQLCODE without regexing the
// formatted message.
func Example_db2Error() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	_, err := db.Exec(`INSERT INTO mylib.things (id) VALUES (?)`, 42)
	if err == nil {
		return
	}
	var dbErr *hostserver.Db2Error
	if !errors.As(err, &dbErr) {
		log.Fatal(err) // not a server-side SQL error -- TCP-level, etc.
	}
	switch {
	case dbErr.IsNotFound():
		// SQLSTATE 02xxx -- no rows matched
	case dbErr.IsConstraintViolation():
		// SQLSTATE 23xxx -- duplicate key, NOT NULL, FK, check
		fmt.Printf("constraint: %s tokens=%v\n", dbErr.SQLState, dbErr.MessageTokens)
	case dbErr.IsLockTimeout():
		// SQLCODE -911/-913 -- safe to retry with backoff
	case dbErr.IsConnectionLost():
		// SQLSTATE 08xxx -- pool will retire the conn
	default:
		log.Printf("SQL%d %s %s: %s", dbErr.SQLCode, dbErr.SQLState, dbErr.MessageID, dbErr.Message)
	}
}

// Example_blobInsert shows binding a BLOB column via a `?` placeholder.
// Small payloads can pass as a plain []byte; the driver detects the
// LOB column from the server-side parameter marker format and routes
// the bytes through a single WRITE_LOB_DATA frame, then EXECUTE
// carries the locator handle in the SQLDA value slot.
func Example_blobInsert() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	payload := []byte{0xCA, 0xFE, 0xBA, 0xBE} // up to a few KB; bigger uses LOBValue
	if _, err := db.Exec(
		`INSERT INTO mylib.images (id, content) VALUES (?, ?)`, 42, payload,
	); err != nil {
		log.Fatal(err)
	}
}

// Example_lobValueStream shows the streamed bind path for large LOBs.
// The driver reads from the io.Reader in 32 KiB chunks and emits
// multiple WRITE_LOB_DATA frames at advancing offsets so the entire
// payload never needs to live in Go memory at once. Length must be
// known up front because the IBM i host server allocates locator
// buffers based on the declared size.
func Example_lobValueStream() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	f, err := os.Open("backup.tar.gz")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	stat, err := f.Stat()
	if err != nil {
		log.Fatal(err)
	}

	val := &db2i.LOBValue{Reader: f, Length: stat.Size()}
	if _, err := db.Exec(
		`INSERT INTO mylib.archives (id, blob) VALUES (?, ?)`, 1, val,
	); err != nil {
		log.Fatal(err)
	}
}

// Example_clobInsert binds a CLOB column. The driver transcodes the
// Go string to the column's declared CCSID via the per-CCSID codec
// in package ebcdic (CCSID 273 / German EBCDIC on a German PUB400
// account, CCSID 37 / US English on a US system, etc.) so EBCDIC
// code-point quirks ("!" = 0x5A in CCSID 37 but 0x4F in CCSID 273)
// round-trip cleanly through the matching read decoder.
func Example_clobInsert() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	doc := "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " +
		"... entire document up to the column's max ..."
	if _, err := db.Exec(
		`INSERT INTO mylib.docs (id, body) VALUES (?, ?)`, 7, doc,
	); err != nil {
		log.Fatal(err)
	}
}

// Example_lobReader streams a BLOB out of a SELECT one chunk at a
// time. The DSN option `?lob=stream` flips the default scan-into-
// []byte behaviour to scan-into-*LOBReader for LOB columns; the
// reader satisfies io.Reader+io.Closer and pulls 32 KiB chunks per
// Read call. Pair with Example_lobValueStream for the bind side.
func Example_lobReader() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB&lob=stream")
	defer db.Close()

	row := db.QueryRow(`SELECT content FROM mylib.images WHERE id = ?`, 42)
	var r *db2i.LOBReader
	if err := row.Scan(&r); err != nil {
		log.Fatal(err)
	}
	defer r.Close()

	if _, err := io.Copy(os.Stdout, r); err != nil {
		log.Fatal(err)
	}
}

// Example_dsnKnobs exercises the three most commonly tuned DSN knobs
// at once: ?lob-threshold=N caps the inline-LOB cutoff the server
// uses for parameter-marker writes; ?ccsid=1208 forces UTF-8 on the
// application-data CCSID so non-ASCII characters round-trip without
// locale-dependent EBCDIC ambiguity; ?tls=true wraps both as-signon
// and as-database sockets in crypto/tls (flipping the default ports
// to 9476 / 9471). The keys are independent -- mix and match per
// deployment.
func Example_dsnKnobs() {
	dsn := "db2i://USER:PASSWORD@host.example.com/" +
		"?library=MYLIB" +
		"&lob-threshold=8192" +
		"&ccsid=1208" +
		"&tls=true" +
		"&tls-server-name=host.example.com"
	db, err := sql.Open("db2i", dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	_ = db.Ping()
}

// Example_libraries pins the `libraries=A,B,C` knob, the multi-
// library counterpart to `library=`. Every entry is added to the
// job's library list at connect time so unqualified SQL names
// resolve without explicit `MYLIB.TABLE` qualification.
//
// Semantics:
//   - The first entry is tagged with EBCDIC indicator 'C' (current
//     SQL schema); the rest with 'L' (append to back of *LIBL).
//   - `?library=X` is the default SQL schema. When both knobs are
//     set and X is not already in the list, X is prepended.
//   - Accepted separators: comma + space (the URL "+" decodes to
//     space, so `?libraries=A+B+C` works).
//
// Useful for RPG/CL migrations where the job profile already
// exposes multiple libraries on *LIBL and the same SQL text must
// resolve names from any of them.
func Example_libraries() {
	dsn := "db2i://USER:PASSWORD@host.example.com/" +
		"?libraries=APPLIB,DATALIB,QGPL"
	db, err := sql.Open("db2i", dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	_ = db.Ping()
}

// Example_contextTimeout shows that QueryContext / ExecContext
// honor ctx cancellation. A canceled ctx unblocks the in-flight
// host-server read via net.Conn.SetDeadline; the call returns
// context.DeadlineExceeded / context.Canceled regardless of which
// I/O step bailed.
func Example_contextTimeout() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	rows, err := db.QueryContext(ctx, `SELECT * FROM huge.table`)
	if errors.Is(err, context.DeadlineExceeded) {
		log.Println("query took longer than 5s; pool will replace the conn")
		return
	}
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
}

// Example_packageCache shows the minimal opt-in for extended-
// dynamic SQL packages + the client-side cache-hit fast path.
//
// Wire flow on the first call against a fresh package:
//
//	CREATE_RPB + PREPARE_DESCRIBE + CHANGE_DESCRIPTOR + OPEN  (cache miss)
//
// After the first call, the server has filed the prepared plan in
// a persistent `*PGM` (10-char wire name derived from the `package=`
// base plus a 4-char session-options hash suffix). Subsequent calls
// with byte-identical SQL hit the cache:
//
//	CREATE_RPB + CHANGE_DESCRIPTOR + OPEN-with-name-override  (cache hit)
//
// The cached 18-byte server-assigned statement name rides in CP
// 0x3806 so the server runs the filed plan without re-preparing.
// See docs/package-caching.md for the operator's guide.
func Example_packageCache() {
	dsn := "db2i://USER:PASSWORD@host.example.com:8471/" +
		"?library=MYLIB" +
		"&extended-dynamic=true" +
		"&package=APP" +
		"&package-library=MYLIB" +
		"&package-cache=true"
	db, err := sql.Open("db2i", dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	// First call -- cache miss; server files the statement.
	row := db.QueryRow(`SELECT label FROM mylib.things WHERE id = ?`, 42)
	var label string
	if err := row.Scan(&label); err != nil {
		log.Fatal(err)
	}

	// Repeated identical SQL hits the cache. With a *slog.Logger
	// attached, observe "db2i: query cache-hit" DEBUG lines.
	for i := 0; i < 100; i++ {
		_ = db.QueryRow(`SELECT label FROM mylib.things WHERE id = ?`, i).Scan(&label)
	}
}

// Example_packageCacheObservability shows how to assert cache-hit
// dispatch happened, either in unit tests or in a structured-log
// pipeline. A *bytes.Buffer-backed slog handler captures every
// DEBUG line the driver emits; the cache-hit dispatch is marked
// by the message text "db2i: exec cache-hit" or
// "db2i: query cache-hit" plus the op attr
// (EXECUTE_PREPARED_CACHED / OPEN_SELECT_PREPARED_CACHED).
//
// In production, replace bytes.Buffer with whatever sink your
// observability stack uses (slog.NewJSONHandler to stderr,
// otelslog.NewHandler for OTel logs SDK, etc.).
func Example_packageCacheObservability() {
	var buf bytes.Buffer
	logger := slog.New(slog.NewTextHandler(&buf, &slog.HandlerOptions{
		Level: slog.LevelDebug,
	}))

	cfg := db2i.DefaultConfig()
	cfg.Host = "host.example.com"
	cfg.User = "USER"
	cfg.Password = "PASSWORD"
	cfg.Library = "MYLIB"
	cfg.ExtendedDynamic = true
	cfg.PackageName = "APP"
	cfg.PackageLibrary = "MYLIB"
	cfg.PackageCache = true
	cfg.Logger = logger

	connector, err := db2i.NewConnector(&cfg)
	if err != nil {
		log.Fatal(err)
	}
	db := sql.OpenDB(connector)
	defer db.Close()

	const q = `SELECT 1 FROM SYSIBM.SYSDUMMY1`
	_ = db.QueryRow(q).Scan(new(int)) // miss
	_ = db.QueryRow(q).Scan(new(int)) // hit

	// Cross-check in tests / log pipelines:
	if !strings.Contains(buf.String(), "db2i: query cache-hit") {
		log.Println("expected cache-hit dispatch; check package-criteria " +
			"and that the SQL text byte-equals the previous call")
	}
}

// Example_packageCacheCriteria shows the package-criteria knob.
// Default rejects unparameterised SELECT (zero markers) -- the
// SELECT below would NOT be filed. package-criteria=select adds
// it to the cache pool.
//
// Use "select" when your workload has many identical zero-
// parameter SELECTs (typical of dashboards refreshing the same
// metric). Stick with "default" to minimise *PGM size in
// workloads where unparameterised SQL varies.
func Example_packageCacheCriteria() {
	dsn := "db2i://USER:PASSWORD@host.example.com:8471/" +
		"?library=MYLIB" +
		"&extended-dynamic=true" +
		"&package=APP" +
		"&package-library=MYLIB" +
		"&package-cache=true" +
		"&package-criteria=select"
	db, err := sql.Open("db2i", dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	// Filed under "select" criteria; would be rejected under "default".
	row := db.QueryRow(`SELECT CURRENT_TIMESTAMP FROM SYSIBM.SYSDUMMY1`)
	var ts time.Time
	_ = row.Scan(&ts)
}

// Example_batchExec_insert demonstrates Conn.BatchExec for bulk
// INSERT (v0.7.9). N rows pack into one CP 0x381F multi-row
// EXECUTE per 32k-row chunk -- one round-trip vs N for a per-row
// loop. Same wire shape works for UPDATE / DELETE / MERGE.
//
// Access goes through sql.Conn.Raw because BatchExec is a
// driver-typed method, not part of the database/sql interface.
func Example_batchExec_insert() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	ctx := context.Background()
	conn, err := db.Conn(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	rows := make([][]any, 1000)
	for i := range rows {
		rows[i] = []any{int64(i + 1), fmt.Sprintf("row-%04d", i)}
	}

	var affected int64
	err = conn.Raw(func(driverConn any) error {
		d := driverConn.(*db2i.Conn)
		n, err := d.BatchExec(ctx, "INSERT INTO mylib.t (id, label) VALUES (?, ?)", rows)
		affected = n
		return err
	})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("inserted %d rows in one round-trip\n", affected)
}

// Example_batchExec_lob shows that BatchExec accepts LOB binds: any
// row carrying a *db2i.LOBValue routes the whole batch to the
// per-row EXECUTE path, because the locator-allocate flow doesn't
// compose with the multi-row block-insert wire shape. Caller code
// is unchanged; the cost is one round-trip per row rather than
// one per chunk, but per-row is still safer than rolling your own
// loop -- the cumulative affected count and the partial-progress
// error reporting both stay consistent with the fast path. (v0.7.15)
func Example_batchExec_lob() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()
	ctx := context.Background()
	conn, _ := db.Conn(ctx)
	defer conn.Close()

	rows := [][]any{
		{int64(1), []byte("small payload")},
		{int64(2), &db2i.LOBValue{
			Reader: bytes.NewReader(bytes.Repeat([]byte{'A'}, 1<<20)), // 1 MiB
			Length: 1 << 20,
		}},
	}
	conn.Raw(func(driverConn any) error {
		d := driverConn.(*db2i.Conn)
		_, err := d.BatchExec(ctx, "INSERT INTO mylib.blobs (id, payload) VALUES (?, ?)", rows)
		return err
	})
}

// Example_beginTxIsolation pins the isolation level for one
// transaction explicitly (v0.7.15). db.BeginTx routes through
// driver.ConnBeginTx, which translates the sql.IsolationLevel
// constant into the IBM i commitment-control level on CP 0x380E.
//
// Standard mapping:
//
//	sql.LevelDefault         → DSN value (or *CS if DSN unset)
//	sql.LevelReadUncommitted → *CHG
//	sql.LevelReadCommitted   → *CS  (cursor stability)
//	sql.LevelRepeatableRead  → *ALL (read stability)
//	sql.LevelSerializable    → *RR
//
// Unsupported levels (Snapshot, etc.) and TxOptions.ReadOnly
// reject up-front -- IBM i has no session-level read-only flag.
func Example_beginTxIsolation() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()
	ctx := context.Background()

	tx, err := db.BeginTx(ctx, &sql.TxOptions{
		Isolation: sql.LevelSerializable,
	})
	if err != nil {
		log.Fatal(err)
	}
	_, err = tx.ExecContext(ctx, "INSERT INTO mylib.ledger (acct, delta) VALUES (?, ?)", 42, 100)
	if err != nil {
		tx.Rollback()
		log.Fatal(err)
	}
	if err := tx.Commit(); err != nil {
		log.Fatal(err)
	}
}

// Example_savepoint shows the three driver-typed savepoint methods
// added in v0.7.12. Each issues plain SQL (`SAVEPOINT`,
// `RELEASE SAVEPOINT`, `ROLLBACK TO SAVEPOINT`) through the
// connection's Exec path. Savepoints require an active unit of
// work (autocommit off), which BeginTx provides.
func Example_savepoint() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB&isolation=cs")
	defer db.Close()
	ctx := context.Background()
	conn, _ := db.Conn(ctx)
	defer conn.Close()

	tx, _ := conn.BeginTx(ctx, nil)
	tx.ExecContext(ctx, "INSERT INTO mylib.audit (msg) VALUES (?)", "phase 1")

	conn.Raw(func(driverConn any) error {
		d := driverConn.(*db2i.Conn)
		// Mark a savepoint.
		if err := d.Savepoint(ctx, "SP1"); err != nil {
			return err
		}
		// Optional work that we may want to undo.
		if _, err := tx.ExecContext(ctx, "UPDATE mylib.balance SET v = v + ? WHERE id = ?", 100, 1); err != nil {
			// Rolling back to the savepoint preserves earlier
			// statements (phase 1) but unwinds everything since.
			return d.RollbackToSavepoint(ctx, "SP1")
		}
		// Drop the savepoint so the work commits with the outer tx.
		return d.ReleaseSavepoint(ctx, "SP1")
	})
	tx.Commit()
}

// Example_setSchema swaps the default schema mid-session via plain
// SQL (`SET SCHEMA <name>`) without re-opening the connection.
// Useful for multi-tenant services that pin a per-tenant schema
// after auth without thrashing the connection pool. (v0.7.12)
func Example_setSchema() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/")
	defer db.Close()
	ctx := context.Background()
	conn, _ := db.Conn(ctx)
	defer conn.Close()

	conn.Raw(func(driverConn any) error {
		return driverConn.(*db2i.Conn).SetSchema(ctx, "TENANT42")
	})
	// Unqualified names now resolve in TENANT42.
	row := conn.QueryRowContext(ctx, "SELECT COUNT(*) FROM widgets")
	var n int
	row.Scan(&n)
}

// Example_libraries_runtime shows mid-session AddLibraries /
// RemoveLibraries. AddLibraries uses the host-server NDB
// ADD_LIBRARY_LIST flow (one round-trip for N entries).
// RemoveLibraries loops `CALL QSYS2.QCMDEXC('RMVLIBLE LIB(X)')`
// per library — the host server has no NDB REMOVE wire, so
// mid-session shrinking goes through CL. (v0.7.12)
func Example_libraries_runtime() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB&libraries=APPLIB")
	defer db.Close()
	ctx := context.Background()
	conn, _ := db.Conn(ctx)
	defer conn.Close()

	conn.Raw(func(driverConn any) error {
		d := driverConn.(*db2i.Conn)
		// Add three libraries at the end of *LIBL.
		if err := d.AddLibraries(ctx, []string{"DATALIB", "WORKLIB", "QGPL"}); err != nil {
			return err
		}
		// ... do work ...

		// Shrink back. CPF2104 / CPF9810 ("not in list") are
		// downgraded to slog WARN; transient state quirks don't
		// abort the loop.
		return d.RemoveLibraries(ctx, []string{"WORKLIB"})
	})
}

// Example_callWithNamedParameters demonstrates the v0.7.18
// `sql.Named()` binding for stored-procedure CALLs. The driver
// looks up parameter names in QSYS2.SYSPARMS on first use and
// reorders args so each named bind lands in the right slot --
// declaration order in the Go source doesn't have to match the
// proc's declaration order. Cached on the *Stmt for repeat calls.
func Example_callWithNamedParameters() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	// Proc: CREATE PROCEDURE mylib.p_lookup
	//   (IN P_CODE VARCHAR(10), OUT P_NAME VARCHAR(64), OUT P_QTY INTEGER)
	var name string
	var qty int
	_, err := db.Exec("CALL mylib.p_lookup(?, ?, ?)",
		// Bind order in the Go source is intentionally shuffled --
		// the catalog lookup maps each name to the correct slot.
		sql.Named("P_QTY", sql.Out{Dest: &qty}),
		sql.Named("P_CODE", "WIDGET"),
		sql.Named("P_NAME", sql.Out{Dest: &name}),
	)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s has %d in stock\n", strings.TrimSpace(name), qty)
}

// Example_scanAll iterates a result set via the v0.7.12 db2iiter
// adapter and Go 1.23's range-over-func. The yield function
// receives (T, error) per row; break to stop early. Compared to
// the manual `for rows.Next() { rows.Scan ... }` loop, ScanAll
// folds the error-handling into the range expression.
//
// (The adapter lives in github.com/complacentsee/go-db2i/db2iiter
// to keep the core driver import-free of "iter".)
func Example_scanAll() {
	// import "github.com/complacentsee/go-db2i/db2iiter"
	//
	// db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	// defer db.Close()
	// rows, _ := db.Query("SELECT id, name FROM mylib.widgets")
	// defer rows.Close()
	//
	// type widget struct{ ID int; Name string }
	// scan := func(rows *sql.Rows) (widget, error) {
	//     var w widget
	//     return w, rows.Scan(&w.ID, &w.Name)
	// }
	// for w, err := range db2iiter.ScanAll(rows, scan) {
	//     if err != nil { log.Fatal(err) }
	//     use(w)
	// }
}

// Example_nullableScan shows the two standard Go patterns for
// reading columns that may be NULL: a pointer destination (left
// nil on NULL, set to the column value otherwise) and the typed
// sql.NullXxx wrappers from database/sql. Both work without any
// driver-specific setup.
func Example_nullableScan() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	rows, err := db.Query(`SELECT id, label, expires_at FROM mylib.things`)
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	for rows.Next() {
		var id int64
		var label *string         // pointer: nil when the column is NULL
		var expires sql.NullTime  // wrapper: .Valid is false on NULL
		if err := rows.Scan(&id, &label, &expires); err != nil {
			log.Fatal(err)
		}

		labelStr := "(unknown)"
		if label != nil {
			labelStr = *label
		}
		if expires.Valid {
			fmt.Printf("%d %s expires %s\n", id, labelStr, expires.Time.Format(time.RFC3339))
		} else {
			fmt.Printf("%d %s no expiry\n", id, labelStr)
		}
	}
}

// Example_errorRetry shows the typical lock-timeout retry pattern.
// The driver classifies SQLCODE -911 / -913 as a transient lock
// timeout via *hostserver.Db2Error.IsLockTimeout; the caller decides
// the backoff strategy. Other Db2 errors (constraint violations,
// syntax errors, etc.) fall through to the surrounding error path
// unchanged.
func Example_errorRetry() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB&isolation=cs")
	defer db.Close()

	const maxAttempts = 4
	backoff := 50 * time.Millisecond

	var err error
	for attempt := 1; attempt <= maxAttempts; attempt++ {
		_, err = db.Exec(`UPDATE mylib.balance SET v = v - ? WHERE id = ?`, 10, 1)
		if err == nil {
			break
		}
		var dbErr *hostserver.Db2Error
		if !errors.As(err, &dbErr) || !dbErr.IsLockTimeout() {
			log.Fatal(err) // not a lock timeout: surface to the caller
		}
		time.Sleep(backoff)
		backoff *= 2
	}
	if err != nil {
		log.Fatalf("update gave up after %d attempts: %v", maxAttempts, err)
	}
}

// Example_preparedStatementReuse shows that ordinary database/sql
// prepared-statement reuse works as expected: db.Prepare PREPAREs
// the SQL once, and subsequent Exec calls on the returned *sql.Stmt
// reuse the same server-side plan. Enabling the extended-dynamic
// package cache (see Example_packageCache) further amortises the
// PREPARE across processes / connections, but db.Prepare alone is
// enough to avoid re-parsing on a hot loop within one connection.
func Example_preparedStatementReuse() {
	db, _ := sql.Open("db2i", "db2i://u:p@host/?library=MYLIB")
	defer db.Close()

	stmt, err := db.Prepare(`INSERT INTO mylib.events (kind, payload) VALUES (?, ?)`)
	if err != nil {
		log.Fatal(err)
	}
	defer stmt.Close()

	events := []struct {
		kind    string
		payload string
	}{
		{"login", "u=alice"},
		{"login", "u=bob"},
		{"logout", "u=alice"},
	}
	for _, e := range events {
		if _, err := stmt.Exec(e.kind, e.payload); err != nil {
			log.Fatal(err)
		}
	}
}
