package driver

import "testing"

// TestSkipLeadingSQLNoise pins the shared leading-noise scanner that
// feeds firstSQLVerb / isSelect / isCall. It must step over leading
// whitespace and any run of line (`--`) or block (`/* */`) comments so
// the verb token that follows is the real statement verb.
func TestSkipLeadingSQLNoise(t *testing.T) {
	cases := []struct {
		sql  string
		want string // remainder after skipping leading noise
	}{
		{"SELECT 1", "SELECT 1"},
		{"  SELECT 1", "SELECT 1"},
		{"\n\t SELECT 1", "SELECT 1"},
		{"-- banner\nSELECT 1", "SELECT 1"},
		{"--banner\r\nSELECT 1", "SELECT 1"},
		{"/* banner */SELECT 1", "SELECT 1"},
		{"/* banner */ SELECT 1", "SELECT 1"},
		{"/* a */ /* b */\n-- c\nSELECT 1", "SELECT 1"},
		{"  -- one\n  /* two */  CALL p()", "CALL p()"},
		// Unterminated comments consume the rest of the string.
		{"/* never closed", ""},
		{"-- trailing", ""},
		// A comment marker inside the verb region is never treated as
		// a leading comment once the verb has started.
		{"SELECT '--not a comment'", "SELECT '--not a comment'"},
		{"", ""},
	}
	for _, tc := range cases {
		t.Run(tc.sql, func(t *testing.T) {
			got := tc.sql[skipLeadingSQLNoise(tc.sql):]
			if got != tc.want {
				t.Errorf("skipLeadingSQLNoise(%q) -> remainder %q, want %q", tc.sql, got, tc.want)
			}
		})
	}
}

// TestVerbScannersIgnoreLeadingComments is the regression for issue
// #35: leading `--` / `/* */` comments (common in ORM/tool output)
// must not defeat isSelect / isCall / firstSQLVerb classification.
func TestVerbScannersIgnoreLeadingComments(t *testing.T) {
	t.Run("isSelect", func(t *testing.T) {
		yes := []string{
			"SELECT 1 FROM SYSIBM.SYSDUMMY1",
			"-- pick a row\nSELECT 1 FROM SYSIBM.SYSDUMMY1",
			"/* generated by ORM */ SELECT 1 FROM SYSIBM.SYSDUMMY1",
			"/* a */\n-- b\n  VALUES 1",
			"-- cte\nWITH c AS (SELECT 1) SELECT * FROM c",
		}
		for _, s := range yes {
			if !isSelect(s) {
				t.Errorf("isSelect(%q) = false, want true", s)
			}
		}
		no := []string{
			"-- just a comment\nINSERT INTO t VALUES (1)",
			"/* not a select */ CALL p()",
		}
		for _, s := range no {
			if isSelect(s) {
				t.Errorf("isSelect(%q) = true, want false", s)
			}
		}
	})

	t.Run("isCall", func(t *testing.T) {
		yes := []string{
			"CALL mylib.p(?)",
			"-- invoke proc\nCALL mylib.p(?)",
			"/* invoke proc */CALL mylib.p(?)",
			"/* a */ -- b\n  CALL p()",
		}
		for _, s := range yes {
			if !isCall(s) {
				t.Errorf("isCall(%q) = false, want true", s)
			}
		}
		no := []string{
			"-- not a call\nSELECT 1",
			"/* callback */ INSERT INTO t VALUES (1)", // CALLBACK must not match CALL
		}
		for _, s := range no {
			if isCall(s) {
				t.Errorf("isCall(%q) = true, want false", s)
			}
		}
	})

	t.Run("firstSQLVerb", func(t *testing.T) {
		cases := []struct {
			sql  string
			want string
		}{
			{"-- banner\nINSERT INTO t VALUES (?)", "INSERT"},
			{"/* banner */ UPDATE t SET x=?", "UPDATE"},
			{"/* a */ -- b\nDELETE FROM t WHERE id=?", "DELETE"},
			{"  /* banner */CALL p(?)", "CALL"},
		}
		for _, tc := range cases {
			if got := firstSQLVerb(tc.sql); got != tc.want {
				t.Errorf("firstSQLVerb(%q) = %q, want %q", tc.sql, got, tc.want)
			}
		}
	})
}

// TestPackageEligibleFor_LeadingComment confirms the eligibility gate
// (which reads firstSQLVerb) is not fooled by a leading comment: a
// commented parameterised SELECT-FOR-UPDATE must still classify as a
// SELECT and file under the package criteria.
func TestPackageEligibleFor_LeadingComment(t *testing.T) {
	conn := &Conn{
		cfg: &Config{
			ExtendedDynamic: true,
			PackageName:     "APP",
			PackageLibrary:  "QGPL",
			PackageError:    "warning",
			PackageCriteria: "default",
		},
		pkg: &fakePackageManager,
	}
	cases := []struct {
		sql       string
		hasParams bool
		want      bool
	}{
		// INSERT ... SELECT files under default even unparameterised;
		// the leading comment must not hide the INSERT verb.
		{"-- seed\nINSERT INTO T (A) SELECT 1 FROM SYSIBM.SYSDUMMY1", false, true},
		{"/* seed */ INSERT INTO T (A) SELECT 1 FROM SYSIBM.SYSDUMMY1", false, true},
		// SELECT ... FOR UPDATE files under default; comment-led form
		// must classify the same as the bare form.
		{"-- lock\nSELECT * FROM T FOR UPDATE", false, true},
		// A commented plain SELECT (no params) is NOT eligible under
		// default -- same as the bare form, i.e. the comment doesn't
		// flip the answer either way.
		{"-- read\nSELECT 1 FROM SYSIBM.SYSDUMMY1", false, false},
	}
	for _, tc := range cases {
		t.Run(tc.sql, func(t *testing.T) {
			if got := conn.packageEligibleFor(tc.sql, tc.hasParams); got != tc.want {
				t.Errorf("packageEligibleFor(%q, hasParams=%v) = %v, want %v",
					tc.sql, tc.hasParams, got, tc.want)
			}
		})
	}
}
